[package]
name = "pfnext"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.5"
actix-web = "4.5.1"
shuttle-actix-web = "0.43.0"
shuttle-runtime = "0.43.0"
serde = "1.0.148"
shuttle-shared-db = { version = "0.43.0", features = ["postgres", "sqlx"] }
sqlx = "0.7.1"
tokio = "1.26.0"
