branding = "Another Level"

smtp_host = 'smtp.fastmail.com'
smtp_port = 465

email_sender_name = "Another Level Community Fitness"
email_sender_address = "nbartlett@fastmail.net"

email_replyto_name = "Another Level Community Fitness"
email_replyto_address = "nbartlett+anotherlevel@fastmail.net"

email_admin_notifications = "notifications@anotherlevelfitness.uk"

timezone_name = "Europe/London"
