[home]
title = "Home"
url = "/index.html"
nav = true

[about]
title = "About"
url = "/about.html"
nav = true
script = false

[pricing]
title = "Pricing"
url = "/pricing.html"
nav = true
script = false

[sessions]
title = "Sessions"
url = "/sessions.html"
nav = true

[challenges]
title = "Challenges"
url = "/challenges.html"
nav = true

[activities]
title = "Activities"
url = "activities.html"
nav = true

[polls]
title = "Polls"
url = "/polls.html"
nav = true

[bookings]
title = "Bookings"
url = "/bookings.html"

[login]
title = "Login"
url = "/login.html"

[register]
title = "Register"
url = "/register.html"

[passwordreset]
title = "Password Reset"
url = "/passwordreset.html"

[profile]
title = "Profile"
url = "/profile.html"

[attendance]
title = "Session Attendance"
url = "/attendance.html"

[edit_session]
title = "Create/Edit Session"
url = "/edit_session.html"

[feedback]
title = "Session Feedback"
url = "/feedback.html"

[members]
title = "Member Directory"
url = "/members.html"

[logs]
title = "Logs"
url = "/logs.html"

[login_list]
title = "Login List"
url = "/loginlist.html"

[stats]
title = "Attendance Stats"
url = "/stats.html"

[sessions_report]
title = "Sessions Report"
url = "/sessions_report.html"
